services:
  socialbugcrm.module:
    class: SocialBugCRM
    public: true
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'socialbugcrm'

  socialbugcrm.context:
    class: Context
    public: true
    factory: [ 'Context', 'getContext' ]

  #####################
  # PS Account

  ps_accounts.installer:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Installer'
    public: true
    arguments:
      - "5.0"

  ps_accounts.facade:
    class: 'PrestaShop\PsAccountsInstaller\Installer\Facade\PsAccounts'
    public: true
    arguments:
      - "@ps_accounts.installer"

  #####################
  # PS Billing
  ps_billings.context_wrapper:
    class: 'PrestaShopCorp\Billing\Wrappers\BillingContextWrapper'
    # public: false
    arguments:
      - '@ps_accounts.facade'
      - '@socialbugcrm.context'
      - true # if true you are in sandbox mode, if false or empty not in sandbox

  ps_billings.facade:
    class: 'PrestaShopCorp\Billing\Presenter\BillingPresenter'
    public: true
    arguments:
      - '@ps_billings.context_wrapper'
      - '@socialbugcrm.module'
      - '@socialbugcrm.context'

  # Remove this if you don't need BillingService
  ps_billings.service:
    class: PrestaShopCorp\Billing\Services\BillingService
    public: true
    arguments:
      - '@ps_billings.context_wrapper'
      - '@socialbugcrm.module'